name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./admin
      run: yarn
    - name: Run tests
      working-directory: ./admin
      run: yarn test
